name: CI/CD for kbot

on:
  push:
    branches:
      - develop

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  ci:
    name: continious integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set-Up_GOLANG
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'

      - name: Test
        run: make test

      - name: Info
        run: make build-info
